# Generated by Django 6.0.4 on 2026-09-15 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_inventoryitem_rawmaterial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='expiry_basis',
            field=models.CharField(choices=[('label', 'Printed expiry'), ('manufactured', 'Manufacture + shelf life'), ('storage', 'Received + storage life')], default='label', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='guidance_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='manufactured_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='quarantined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='shelf_life_days',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='storage_type',
            field=models.CharField(choices=[('chilled', 'Chilled'), ('frozen', 'Frozen'), ('ambient', 'Ambient')], default='chilled', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('standard', 'Owner delivery'), ('express', 'Express request')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='inventory_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='preparation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='daily_capacity',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='lead_hours',
            field=models.PositiveIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='preparation_minutes',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='social_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('cooked', 'Cooked'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]


def mark_legacy_orders(apps, schema_editor):
    # Earlier checkout deducted stock immediately, including pending orders.
    apps.get_model('myapp', 'Order').objects.all().update(inventory_deducted=True)

Migration.operations.append(migrations.RunPython(mark_legacy_orders, migrations.RunPython.noop))
