# Generated by Django 6.0.4 on 2026-09-15 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_storefront_order_discount_amount_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
            ],
            options={
                'unique_together': {('order', 'event')},
            },
        ),
    ]
