# Generated by Django 6.0.4 on 2026-09-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_orderreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefront',
            name='food_philosophy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storefront',
            name='founder_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='storefront',
            name='founder_intro',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='storefront',
            name='founder_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='storefront',
            name='founding_story',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storefront',
            name='service_area',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='storefront',
            name='signature_food',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='storefront',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
