# Generated by Django 6.0.4 on 2026-09-15 08:44

from django.conf import settings
from django.db import migrations, models


def preserve_addresses(apps, schema_editor):
    Address = apps.get_model('myapp', 'Address')
    Order = apps.get_model('myapp', 'Order')
    alias = schema_editor.connection.alias
    for order in Order.objects.using(alias).filter(address__isnull=False).iterator():
        address = Address.objects.using(alias).filter(pk=order.address_id).values().first()
        order.delivery_address = address or {}
        order.save(using=alias, update_fields=['delivery_address'])
    for user_id in Address.objects.using(alias).values_list('user_id', flat=True).distinct():
        addresses = Address.objects.using(alias).filter(user_id=user_id)
        chosen = addresses.order_by('-is_default', '-id').first()
        addresses.update(is_default=False)
        addresses.filter(pk=chosen.pk).update(is_default=True)


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_storefront_food_philosophy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(preserve_addresses, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='one_default_address_per_user'),
        ),
    ]
