# Generated by Django 6.0.4 on 2026-09-19 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_address_recipient_name_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preparation_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='preparation_plan',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_batch_minutes',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='batch_size',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='max_early_minutes',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='product',
            name='max_preparation_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='product',
            name='packing_minutes_per_portion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='preparation_tasks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='storefront',
            name='kitchen_close_hour',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='storefront',
            name='kitchen_open_hour',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.CreateModel(
            name='KitchenBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('reason', models.CharField(default='Kitchen unavailable', max_length=160)),
            ],
            options={
                'ordering': ['start_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='kitchen_block_end_after_start')],
            },
        ),
    ]
