# Generated by Django 6.0.4 on 2026-09-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_preserve_existing_preparation_windows'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_instructions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='storefront',
            name='bank_transfer_instructions',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='storefront',
            name='duitnow_qr_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='storefront',
            name='manual_payment_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
