# Generated by Django 6.0.4 on 2026-09-25 00:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_order_payment_instructions_order_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('voided', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('utilities', 'Utilities'), ('delivery', 'Courier / transport'), ('labour', 'Labour'), ('marketing', 'Marketing'), ('other', 'Other overhead')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('note', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='after_open_days',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='after_thaw_days',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='handling_history',
            field=models.CharField(choices=[('not_recorded', 'Not recorded'), ('documented', 'Storage history documented'), ('unknown', 'Uncertain handling'), ('breach', 'Known storage breach')], default='not_recorded', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='handling_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='label_date_type',
            field=models.CharField(choices=[('use_by', 'Use by / expiry'), ('best_before', 'Best before'), ('not_recorded', 'Not recorded')], default='not_recorded', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='opened_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='original_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='source_type',
            field=models.CharField(choices=[('packaged', 'Packaged retail'), ('market', 'Wet market / unpackaged'), ('other', 'Other / not recorded')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='thawed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='estimated_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('reason', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.inventoryitem')),
            ],
        ),
    ]
