# Generated by Django 6.0.4 on 2026-10-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_legacy_commitment_baselines'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selling_status',
            field=models.CharField(choices=[('active', 'Accepting orders'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=10),
        ),
    ]
