# Generated by Django 6.0.4 on 2026-10-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_product_selling_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_weekdays',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
