import {useEffect,useState,useRef} from 'react';
import axios from 'axios';
import {apiError} from '../utils/apiError';
import {getCookie} from '../utils/cookieUtils';
import {malaysiaDate} from '../utils/planner';
const money=v=>v==null?'Not recorded':'RM '+Number(v).toFixed(2);
export default function CostPanel(){
 const [report,setReport]=useState(null),[materials,setMaterials]=useState([]),[lots,setLots]=useState([]),[expenses,setExpenses]=useState([]);
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0);
 const [range,setRange]=useState({start:malaysiaDate(new Date(Date.now()-27*86400000)),end:malaysiaDate(new Date())});
 const [expense,setExpense]=useState({date:malaysiaDate(new Date()),category:'utilities',amount:'',note:''});
 const [waste,setWaste]=useState({inventory_item:'',quantity:'',reason:''});
 const expenseKey=useRef(crypto.randomUUID()),wasteKey=useRef(crypto.randomUUID());
 useEffect(()=>{const c=new AbortController();setError('');setReport(null);
 Promise.all([axios.get('/api/admin/costs/',{params:range,signal:c.signal}),axios.get('/api/admin/raw-materials/',{signal:c.signal}),axios.get('/api/admin/inventory-items/',{signal:c.signal}),axios.get('/api/admin/expenses/',{signal:c.signal})]).then(([a,b,d,e])=>{setReport(a.data);setMaterials(b.data);setLots(d.data);setExpenses(e.data)}).catch(e=>{if(!axios.isCancel(e))setError(apiError(e))});return()=>c.abort()},[range,retry]);
 const mutate=async(url,data,method='post')=>{if(busy)return false;setBusy(true);setError('');setMessage('');try{await axios[method](url,data,{headers:{'X-CSRFToken':getCookie('csrftoken')}});setRetry(n=>n+1);setMessage('Saved.');return true}catch(e){setError(apiError(e));return false}finally{setBusy(false)}};
 return <section className="cost-workspace"><h2>Costs, wastage and pricing</h2><p>Menu estimates use today's ingredient costs and packaging. They exclude discounts, labour, delivery, overhead and tax; they are not net profit.</p>
 <div className="admin-fields">{['start','end'].map(key=><label key={key}>{key==='start'?'Period starts':'Period ends'}<input type="date" value={range[key]} onChange={e=>e.target.value && setRange({...range,[key]:e.target.value})}/></label>)}</div>
 {error && <p role="alert">{error} <button onClick={()=>setRetry(n=>n+1)}>Retry</button></p>}<p role="status">{message}</p>
 {!report && !error && <p role="status">Loading costs...</p>}
 {report && <><div className="admin-metrics"><article><span>Operating expenses in period</span><strong>{money(report.operating_expenses)}</strong></article><article><span>Recorded wastage cost in period</span><strong>{money(report.known_waste_cost)}</strong><small>{report.unpriced_waste_records} waste records have unknown costs, excluded from this total.</small></article></div>
 <h3>Current menu contribution estimates · per portion</h3><p>Contribution = menu price minus ingredient estimate minus packaging. Dates above filter expenses and wastage, not these current recipe estimates.</p>
 {report.menus.map(m=><article className="admin-order-summary" key={m.id}><h3>{m.name}</h3><p>Price {money(m.price)} / Ingredients {money(m.ingredient_cost)} / Packaging {money(m.packaging_cost)}</p>{m.missing.length?<p>Complete these costs first: {m.missing.join(', ')}.</p>:<p><strong>Estimated contribution: {money(m.estimated_contribution)} ({m.estimated_margin_percent}%)</strong> before other costs and discounts.</p>}</article>)}
 <details className="settings-group"><summary>Ingredient cost assumptions</summary><p>Enter RM per ingredient inventory unit. RM 12 per kg is RM 0.012 per gram. Update these when supplier prices change. Set packaging costs in Menus.</p>{materials.map(m=><form className="cost-input-row" key={m.id} onSubmit={e=>{e.preventDefault();mutate('/api/admin/raw-materials/'+m.id+'/',{estimated_unit_cost:m.estimated_unit_cost===''?null:m.estimated_unit_cost},'patch')}}><label>{m.name} · RM/{m.unit}<input type="number" min="0" step="0.000001" value={m.estimated_unit_cost ?? ''} onChange={e=>setMaterials(rows=>rows.map(x=>x.id===m.id?{...x,estimated_unit_cost:e.target.value}:x))}/></label><button disabled={busy}>Save cost</button></form>)}</details>
 <details className="settings-group"><summary>Record an operating expense</summary><p>Use for overhead, courier fees, labour or marketing. Do not enter ingredient purchases or packaging here and also count them as recipe costs when calculating a margin.</p>
 <form onSubmit={async e=>{e.preventDefault();if(await mutate('/api/admin/expenses/',{...expense,request_id:expenseKey.current})){expenseKey.current=crypto.randomUUID();setExpense({...expense,amount:'',note:''})}}}>
 <div className="admin-fields"><label>Date<input type="date" required value={expense.date} onChange={e=>setExpense({...expense,date:e.target.value})}/></label><label>Category<select value={expense.category} onChange={e=>setExpense({...expense,category:e.target.value})}>{['utilities','delivery','labour','marketing','other'].map(c=><option key={c}>{c}</option>)}</select></label><label>Amount (RM)<input type="number" required min="0.01" step="0.01" value={expense.amount} onChange={e=>setExpense({...expense,amount:e.target.value})}/></label><label>Receipt / description<input required maxLength={300} value={expense.note} onChange={e=>setExpense({...expense,note:e.target.value})}/></label></div><button disabled={busy}>Record expense</button></form></details>
 <details className="settings-group"><summary>Record ingredient wastage</summary><p>This deducts quantity from the selected batch and records its cost at that time. Use this for discarded ingredients, not items already deducted for cooking. Check the quantity before saving.</p>
 <form onSubmit={async e=>{e.preventDefault();if(await mutate('/api/admin/waste/',{...waste,request_id:wasteKey.current})){wasteKey.current=crypto.randomUUID();setWaste({inventory_item:'',quantity:'',reason:''})}}}><label>Batch<select required value={waste.inventory_item} onChange={e=>setWaste({...waste,inventory_item:e.target.value})}><option value="">Choose stock</option>{lots.filter(l=>Number(l.quantity)>0).map(l=><option key={l.id} value={l.id}>{l.raw_material_name} / {l.batch_code || '#'+l.id} / {l.quantity} {l.unit} remaining</option>)}</select></label><div className="admin-fields"><label>Quantity (batch inventory unit)<input type="number" required min="0.001" step="0.001" value={waste.quantity} onChange={e=>setWaste({...waste,quantity:e.target.value})}/></label><label>Reason<input required maxLength={300} value={waste.reason} onChange={e=>setWaste({...waste,reason:e.target.value})}/></label></div><button disabled={busy}>Record waste and deduct stock</button></form></details>
 <details className="settings-group"><summary>Expense ledger · latest 100 records</summary>{expenses.map(e=><article className="admin-order-summary" key={e.id}><strong>{e.date} · {e.category} · {money(e.amount)}</strong><p>{e.note}</p>{e.voided?<span>Voided — excluded from totals</span>:<button disabled={busy} onClick={()=>mutate('/api/admin/expenses/'+e.id+'/void/',{})}>Void incorrect entry</button>}</article>)}</details>
 <details className="settings-group"><summary>Wastage ledger · selected period, latest 100</summary>{report.waste.map(w=><article className="admin-order-summary" key={w.id}><strong>{w.material}: {w.quantity} {w.unit} · {money(w.cost)}</strong><p>{w.date} · {w.reason}</p></article>)}</details>
 </>}
 </section>
}
