import {useEffect,useState} from 'react';
import axios from 'axios';
export function KitchenHero(){
 const [store,setStore]=useState(null),[ms,setMs]=useState(false);
 useEffect(()=>{axios.get('/api/storefront/').then(r=>setStore(r.data)).catch(()=>{});},[]);
 return <><section className="dk-hero"><div><div className="dk-eyebrow">{ms?'DAPUR RUMAH · DIBUAT MENGIKUT TEMPAHAN':'HOME KITCHEN · MADE TO ORDER'}</div><h1>{ms?'Rasa seperti di rumah. Dirancang untuk anda.':<>A little planning.<br/>A lot of home.</>}</h1><p>{store?.tagline || 'From our home kitchen to your table.'}</p><p>{ms?'Tempah hidangan kegemaran anda lebih awal. Pilih tarikh dan masa penghantaran yang sesuai.':'Your favourite meals, thoughtfully prepared. Choose your food, plan your delivery, and leave the cooking to us.'}</p><div className="dk-actions"><a className="dk-primary" href="#menu">{ms?'Lihat menu':'Explore the menu'} ↗</a><a href="#our-story">{ms?'Kisah kami':'Meet your kitchen'}</a></div><button className="dk-language" onClick={()=>setMs(!ms)}>{ms?'English':'Bahasa Melayu'}</button></div><div className="dk-hero-art" role="img" aria-label="A home kitchen meal, prepared with care"><span className="dk-art-label">THE COMFORT OF HOME</span><div className="dk-plate"><span>🍚</span><span>🥬</span><span>🍗</span></div><div className="dk-art-note">Made with care.<br/>Worth planning for.</div></div></section><div className="dk-benefits"><span>01 · Choose your favourites</span><span>02 · Pick your delivery date</span><span>03 · We prepare with care</span></div><section className="dk-story" id="our-story"><span className="dk-eyebrow">{store?.name || 'Dapur Kita'} / OUR STORY</span><h2>Good food starts in a home kitchen.</h2><p>{store?.story}</p>{store?.contact_email && <p><a href={`mailto:${store.contact_email}`}>Contact the kitchen</a></p>}{store?.social_url && <a href={store.social_url} target="_blank" rel="noreferrer">Follow our kitchen ↗</a>}{store?.bulk_discount_percent>0 && <p className="dk-offer">Order {store.bulk_minimum}+ portions and save {store.bulk_discount_percent}% on food. Applied automatically at checkout.</p>}</section><div id="menu" className="dk-menu-heading"><div><span className="dk-eyebrow">SOMETHING TO LOOK FORWARD TO</span><h2>What are you craving?</h2></div><span>Preorder · Made in small batches</span></div></>;
}
const answers=[['How far ahead can I order?','Choose a delivery date up to 90 days ahead. Each menu has its own advance notice and daily portion limit. Checkout checks these before accepting an order.'],['Can I request express delivery?','Yes, choose an express request at checkout. Menu preparation limits still apply. The owner must confirm courier availability and agree any extra charges with you.'],['What does ingredient freshness mean?','It is an estimate based on recorded batch dates and storage guidance, not a food-safety test. Ingredients that are expired or held are excluded from cooking stock. Future orders may use ingredients purchased later.'],['Can I order meals and snacks?','Yes. Home kitchens can offer lunch boxes, family meals, kuih, baked goods and celebration food. Browse this kitchen’s menu for what is available.'],['What about allergies?','Contact the owner before ordering if you have an allergy. Recipe and storage records do not establish an allergen-free kitchen.'],['How do reviews work?','After an order is delivered, sign in and open the menu item to leave one review per menu.']];
export function KitchenFooter(){
 const [open,setOpen]=useState(false),[answer,setAnswer]=useState('Choose a question below. This is a guided help assistant.');
 return <><section className="dk-faq" id="faq"><span className="dk-eyebrow">A LITTLE HELP BEFORE YOU ORDER</span><h2>Questions from our table</h2>{answers.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section><footer className="dk-footer"><h2>Your next meal, already planned.</h2><a className="dk-primary" href="#menu">Find your favourite ↗</a><p>Dapur Kita · A home kitchen storefront · Prices in MYR</p></footer><button className="dk-help-toggle" onClick={()=>setOpen(!open)} aria-expanded={open}>Kitchen help {open?'×':'?'}</button>{open && <aside className="dk-help" aria-label="Kitchen help"><h3>How can we help?</h3><p role="status">{answer}</p>{answers.map(([q,a])=><button key={q} onClick={()=>setAnswer(a)}>{q}</button>)}</aside>}</>;
}
