import {useEffect,useState} from 'react';
import axios from 'axios';
import {apiError} from '../utils/apiError';
import {getCookie} from '../utils/cookieUtils';
export default function KitchenAvailability(){
 const [blocks,setBlocks]=useState([]),[form,setForm]=useState({start_at:'',end_at:'',reason:''}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const c=new AbortController();axios.get('/api/admin/kitchen-blocks/',{signal:c.signal}).then(r=>{setBlocks(r.data);setError('')}).catch(e=>{if(!axios.isCancel(e))setError(apiError(e))});return()=>c.abort();},[retry]);
 const save=async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await axios.post('/api/admin/kitchen-blocks/',{...form,start_at:form.start_at+':00+08:00',end_at:form.end_at+':00+08:00'},{headers:{'X-CSRFToken':getCookie('csrftoken')}});setBlocks(b=>[...b,r.data].sort((a,b)=>a.start_at.localeCompare(b.start_at)));setForm({start_at:'',end_at:'',reason:''});}catch(e){setError(apiError(e))}finally{setBusy(false)}};
 const remove=async id=>{setBusy(true);setError('');try{await axios.delete(`/api/admin/kitchen-blocks/${id}/`,{headers:{'X-CSRFToken':getCookie('csrftoken')}});setBlocks(b=>b.filter(x=>x.id!==id));}catch(e){setError(apiError(e))}finally{setBusy(false)}};
 return <section className="dk-panel"><h2>Kitchen availability</h2><p>Block closures, breaks or delivery runs before accepting bookings. A block reserves all equipment and work, including unattended steps.</p><details><summary>Manage unavailable time</summary><form onSubmit={save}><label>From (Malaysia time)<input type="datetime-local" required value={form.start_at} onChange={e=>setForm({...form,start_at:e.target.value})}/></label><label>Until<input type="datetime-local" required min={form.start_at} value={form.end_at} onChange={e=>setForm({...form,end_at:e.target.value})}/></label><label>Reason<input required maxLength={160} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><button disabled={busy}>{busy?'Saving...':'Block time'}</button></form>{blocks.map(b=><article key={b.id}><p><strong>{b.reason}</strong><br/>{new Date(b.start_at).toLocaleString('en-MY',{timeZone:'Asia/Kuala_Lumpur'})} to {new Date(b.end_at).toLocaleString('en-MY',{timeZone:'Asia/Kuala_Lumpur'})}</p><button disabled={busy} onClick={()=>remove(b.id)}>Remove block</button></article>)}</details>{error && <div role="alert"><p>{error}</p><button disabled={busy} onClick={()=>setRetry(n=>n+1)}>Reload availability</button></div>}</section>;
}
