import {duration} from '../utils/planner';
const resources=[['prep_table','Prep table'],['stove','Stove'],['oven','Oven'],['rice_cooker','Rice cooker'],['fridge','Fridge space'],['packing_area','Packing area'],['none','No equipment']];
export default function PreparationTasks({value,onChange}){
 const tasks=value.preparation_tasks || [];
 const change=rows=>onChange({...value,preparation_tasks:rows});
 const update=(i,patch)=>change(tasks.map((t,n)=>n===i?{...t,...patch}:t));
 const move=(i,delta)=>{const rows=[...tasks];[rows[i],rows[i+delta]]=[rows[i+delta],rows[i]];change(rows)};
 return <section className="preparation-editor"><h3>Preparation steps</h3><p>Add the actual steps in order, including packing. These appear individually in the planner.</p>
 {tasks.length>0 && <p className="batch-help"><strong>One-batch total: {duration(tasks.reduce((n,t)=>n+Number(t.minutes || 0),0))}</strong><br/>Hands-on: {duration(tasks.filter(t=>t.worker).reduce((n,t)=>n+Number(t.minutes || 0),0))}. Waiting between steps is excluded. The order planner scales these times by the number of batches and shows the actual elapsed window.</p>}{tasks.length===0 && <p className="admin-notice">No detailed steps yet. New orders currently use a basic cook-and-pack estimate.</p>}
 {tasks.map((task,i)=><fieldset key={i}><legend>Step {i+1}: {task.name || 'New step'}</legend><div className="task-fields"><label>What needs doing?<input required maxLength={80} placeholder="e.g. Prepare ingredients" value={task.name} onChange={e=>update(i,{name:e.target.value})}/></label><label>First batch duration (minutes)<input required type="number" min="1" max="43200" value={task.minutes} onChange={e=>update(i,{minutes:e.target.value===''?'':Number(e.target.value)})}/></label><label>Equipment<select value={task.resource} onChange={e=>update(i,{resource:e.target.value,overnight:['fridge','none'].includes(e.target.value)?task.overnight:false})}>{resources.map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label>Does someone need to stay with it?<select value={task.worker?'yes':'no'} onChange={e=>update(i,{worker:e.target.value==='yes',overnight:e.target.value==='yes'?false:task.overnight})}><option value="yes">Yes - hands-on throughout</option><option value="no">No - unattended after setup</option></select></label></div>
 <details><summary>Batch timing and advance preparation</summary><div className="task-fields"><label>Minutes for each extra batch<input required type="number" min="0" max="43200" value={task.additional_batch_minutes} onChange={e=>update(i,{additional_batch_minutes:e.target.value===''?'':Number(e.target.value)})}/></label><label>Allowed wait before the next step (minutes)<input required type="number" min="0" max="10080" value={task.max_wait_minutes} onChange={e=>update(i,{max_wait_minutes:e.target.value===''?'':Number(e.target.value)})}/></label>{!task.worker && ['fridge','none'].includes(task.resource) && <label>Can this rest continue overnight?<select value={task.overnight?'yes':'no'} onChange={e=>update(i,{overnight:e.target.value==='yes'})}><option value="no">Working hours only</option><option value="yes">Allow outside working hours</option></select></label>}</div><p>Zero wait keeps steps together. Allow a gap only when your handling process permits it. Split occasional attention into setup, unattended time and finishing steps.</p></details>
 <div className="admin-toolbar"><button type="button" disabled={i===0} onClick={()=>move(i,-1)} aria-label={`Move step ${i+1} up`}>Move up</button><button type="button" disabled={i===tasks.length-1} onClick={()=>move(i,1)} aria-label={`Move step ${i+1} down`}>Move down</button><button type="button" onClick={()=>change(tasks.filter((_,n)=>n!==i))}>Remove step</button></div></fieldset>)}
 <button type="button" disabled={tasks.length>=20} onClick={()=>change([...tasks,{name:'',minutes:15,additional_batch_minutes:15,resource:'prep_table',worker:true,overnight:false,max_wait_minutes:0}])}>Add preparation step</button><p>Timings are your estimates. One batch uses the portions-per-batch setting above. 1 hour = 60 minutes.</p></section>;
}
