const resources=[['prep_table','Prep table'],['stove','Stove'],['oven','Oven'],['rice_cooker','Rice cooker'],['fridge','Fridge space'],['packing_area','Packing area'],['none','No equipment']];
export default function PreparationTasks({value,onChange}){
 const tasks=value.preparation_tasks || [];
 const update=(i,key,v)=>onChange({...value,preparation_tasks:tasks.map((t,n)=>n===i?{...t,[key]:v}:t)});
 return <section className="preparation-editor"><h3>Preparation steps</h3><p>Add steps in the order you perform them, including packing. Leave empty to use the simple cooking and packing estimate above.</p><p>One worker and one of each resource are available. For occasional attention, add separate setup, unattended and finishing steps. Minutes may span hours or days (4 hours = 240 minutes).</p>
 {tasks.map((task,i)=><fieldset key={i} className="task-editor"><legend>Step {i+1}</legend><div className="task-fields"><label>Task name<input required maxLength={80} value={task.name} onChange={e=>update(i,'name',e.target.value)}/></label><label>Equipment<select value={task.resource} onChange={e=>{const resource=e.target.value;onChange({...value,preparation_tasks:tasks.map((t,n)=>n===i?{...t,resource,overnight:['fridge','none'].includes(resource)?t.overnight:false}:t)})}}>{resources.map(([key,name])=><option value={key} key={key}>{name}</option>)}</select></label>
 {[['minutes','First batch (minutes)',1,43200],['additional_batch_minutes','Each extra batch (minutes)',0,43200],['max_wait_minutes','Allowed gap before next step (minutes)',0,10080]].map(([key,label,min,max])=><label key={key}>{label}<input type="number" required min={min} max={max} value={task[key]} onChange={e=>update(i,key,e.target.value===''?'':Number(e.target.value))}/></label>)}
 <label>Hands-on attention<select value={task.worker?'yes':'no'} onChange={e=>{const worker=e.target.value==='yes';onChange({...value,preparation_tasks:tasks.map((t,n)=>n===i?{...t,worker,overnight:worker?false:t.overnight}:t)})}}><option value="yes">Worker needed throughout</option><option value="no">Unattended after setup</option></select></label>
 {!task.worker && ['fridge','none'].includes(task.resource) && <label>Outside working hours<select value={task.overnight?'yes':'no'} onChange={e=>update(i,'overnight',e.target.value==='yes')}><option value="no">Working hours only</option><option value="yes">Allow unattended rest overnight</option></select></label>}</div>
 <button type="button" onClick={()=>onChange({...value,preparation_tasks:tasks.filter((_,n)=>n!==i)})}>Remove step</button></fieldset>)}
 <button type="button" disabled={tasks.length>=20} onClick={()=>onChange({...value,preparation_tasks:[...tasks,{name:'',minutes:15,additional_batch_minutes:15,resource:'prep_table',worker:true,overnight:false,max_wait_minutes:0}]})}>Add preparation step</button>
 <p className="dk-note">A gap of 0 keeps steps together. Allow longer gaps only when your documented storage and handling process permits them. Scheduling does not validate food safety. Extra-batch time of 0 means all portions fit that step together; check equipment capacity.</p></section>;
}
