import assert from 'node:assert/strict';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {MemoryRouter} from 'react-router-dom';
import {createServer} from 'vite';
const server=await createServer({server:{middlewareMode:true},appType:'custom'});
try{
 const {default:MenuListingStatus}=await server.ssrLoadModule('/src/components/MenuListingStatus.jsx');
 const status=p=>renderToStaticMarkup(createElement(MenuListingStatus,p));
 assert.match(status({error:true,count:0,shown:0}),/temporarily unavailable/);
 assert.doesNotMatch(status({error:true,count:0,shown:0}),/0 items found/);
 assert.match(status({loading:true,count:0,shown:0}),/Loading menu/);
 assert.match(status({count:1,shown:1}),/1 item found/);
 const {default:PaymentOptions}=await server.ssrLoadModule('/src/components/PaymentOptions.jsx');
 const payment=p=>renderToStaticMarkup(createElement(MemoryRouter,null,createElement(PaymentOptions,{value:'cod',onChange:()=>{},...p})));
 const html=payment({manualEnabled:true});
 assert.match(html,/Cash on delivery/);assert.match(html,/DuitNow QR/);
 const demo=html.slice(html.indexOf('<details'));
 assert.match(demo,/Demo credit wallet/);assert.doesNotMatch(demo,/<details[^>]*\sopen/);
 assert.doesNotMatch(payment({manualEnabled:false}),/DuitNow QR/);
 assert.match(payment({value:'wallet'}),/demo wallet selected/);
 const {default:BasketDeliveryDays}=await server.ssrLoadModule('/src/components/BasketDeliveryDays.jsx');
 const basket=(cart,value='')=>renderToStaticMarkup(createElement(MemoryRouter,null,createElement(BasketDeliveryDays,{cart,value})));
 const meal=(name,delivery_weekdays)=>({product:{name,delivery_weekdays}});
 assert.equal(basket([meal('Everyday',[])]),'');
 assert.match(basket([meal('Weekend',[5,6])]),/Saturday, Sunday/);
 const conflict=basket([meal('Monday',[0]),meal('Saturday',[5])]);
 assert.match(conflict,/no delivery weekday in common/);
 assert.match(conflict,/href="\/cart"/);
 const inBasket=renderToStaticMarkup(createElement(MemoryRouter,null,createElement(BasketDeliveryDays,{cart:[meal('Monday',[0]),meal('Saturday',[5])],value:'',showBasketLink:false})));
 assert.match(inBasket,/no delivery weekday in common/);
 assert.doesNotMatch(inBasket,/href="\/cart"/);
 assert.match(basket([meal('Saturday',[5])],'2026-10-11T16:00'),/cannot be delivered/);
 console.log('Product UX: loading/error counts, enabled payment options and collapsed demo disclosure passed.');
}finally{await server.close();}
