import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import axios from 'axios';
import {apiError,readApiError} from '../../utils/apiError';
import {getCookie} from '../../utils/cookieUtils';
import './CheckoutPage.css';
const empty={recipient_name:'',phone:'',line1:'',line2:'',city:'',state:'',postal_code:'',country:'Malaysia'};
const states=['Johor','Kedah','Kelantan','Melaka','Negeri Sembilan','Pahang','Penang','Perak','Perlis','Sabah','Sarawak','Selangor','Terengganu','Kuala Lumpur','Labuan','Putrajaya'];
function AccountSection({title,url,initial,children}){
 const [value,setValue]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 useEffect(()=>{const c=new AbortController();axios.get(url,{signal:c.signal}).then(r=>setValue(r.data || initial)).catch(e=>{if(!axios.isCancel(e))setError(readApiError(e));});return()=>c.abort();},[url,initial,revision]);
 const save=async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');setMessage('');try{const r=await axios({url,method:url==='/api/account/'?'patch':'put',data:value,headers:{'X-CSRFToken':getCookie('csrftoken')}});setValue(r.data);setMessage('Saved.');}catch(e){setError(apiError(e));}finally{setBusy(false);}};
 return <section className="checkout-section"><h2>{title}</h2>{error && <p role="alert">{error}</p>}{!value ? <><p role="status">{error?'Could not load these details.':'Loading...'}</p>{error && <button onClick={()=>{setError('');setRevision(n=>n+1);}}>Try again</button>}</>:<form className="address-form" onSubmit={save}>{children(value,setValue)}<div className="checkout-actions"><button className="checkout-submit" disabled={busy}>{busy?'Saving...':`Save ${title.toLowerCase()}`}</button><span role="status">{message}</span></div></form>}</section>;
}
const profile={first_name:'',last_name:''};
export default function AccountPage(){return <main className="checkout-container account-settings"><h1 className="checkout-title">Account settings</h1><p className="checkout-intro">Manage your name and the delivery address used for future orders.</p><AccountSection title="Profile" url="/api/account/" initial={profile}>{(value,setValue)=><div className="address-fields"><label>Username<input value={value.username || ''} readOnly/></label>{['first_name','last_name'].map((key,i)=><label key={key}>{i?'Last name':'First name'}<input maxLength={150} autoComplete={i?'family-name':'given-name'} value={value[key]} onChange={e=>setValue({...value,[key]:e.target.value})}/></label>)}</div>}</AccountSection><AccountSection title="Delivery address" url="/api/address/" initial={empty}>{(value,setValue)=><><p>Changing your saved address will not change orders already placed. Confirm the address at checkout before ordering.</p><div className="address-fields">{[['recipient_name','Recipient name','name'],['phone','Phone number','tel'],['line1','Street address','address-line1'],['line2','Apartment, floor or unit (optional)','address-line2'],['city','City','address-level2'],['postal_code','Postcode','postal-code']].map(([key,label,auto])=><label key={key}>{label}<input type={key==='phone'?'tel':'text'} autoComplete={auto} required={key!=='line2'} pattern={key==='postal_code'?'[0-9]{5}':undefined} maxLength={key==='postal_code'?5:key==='phone'?20:150} value={value[key] || ''} onChange={e=>setValue({...value,[key]:e.target.value})}/></label>)}<label>State / territory<select required value={value.state} onChange={e=>setValue({...value,state:e.target.value})}><option value="">Choose a state</option>{states.map(s=><option key={s}>{s}</option>)}</select></label><label>Country<input value="Malaysia" readOnly/></label></div></>}</AccountSection><Link className="checkout-back" to="/checkout">Continue to checkout</Link></main>;}
