import {useState,useEffect} from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRight,CalendarDays,Heart,ChefHat,Clock,ShoppingBag,Mail,MapPin,MessageCircle} from 'lucide-react';
import {useStorefront} from '../../contexts/StorefrontProvider';
import {useProduct} from '../../contexts/ProductProvider';
import {Reveal,PageMeta,PrimaryLink,FAQ} from '../../components/BusinessLayout';
export function HomePage(){
 const {store}=useStorefront();const {products,fetchProducts}=useProduct();const [occasion,setOccasion]=useState('Everyday favourites');
 useEffect(()=>{fetchProducts(true)},[fetchProducts]);
 const occasions={'Everyday favourites':'Give your next meal a place in the diary. Browse what this kitchen is offering and choose a delivery date that works for you.','A little treat':'Make room for something to look forward to. Explore the current menu for a snack, a sweet bite, or a favourite worth ordering again.','Something to share':'Planning for more than one? Check portion availability, explore any bulk offer, and speak to the owner about your gathering.'};
 const featured=products.slice(0,3);
 return <main className="business-page"><PageMeta title="Food worth planning for" description="Discover a home kitchen, explore the menu and preorder food with a delivery date that fits your plans."/>
 <section className="business-hero"><Reveal><span className="dk-eyebrow">A HOME KITCHEN. A MORE PERSONAL WAY TO ORDER.</span><h1>Good food.<br/>A little closer<br/><em>to home.</em></h1><p className="business-lead">{store.tagline}</p><p>For the everyday meals and little occasions worth looking forward to. Explore the menu, choose your date, and make a plan with the kitchen behind your food.</p><div className="dk-actions"><PrimaryLink/><Link className="text-link" to="/story">The person behind the food <ArrowUpRight size={16}/></Link></div></Reveal><Reveal className="business-hero-visual"><div className="visual-orbit"/><span className="visual-word">made<br/><em>personal.</em></span><div className="visual-note"><Heart size={20}/><span>A kitchen with a name.<br/>An order with a plan.</span></div><span className="visual-stamp">{store.name}</span></Reveal></section>
 <div className="business-proof"><span><ChefHat size={19}/>One kitchen, its own menu</span><span><CalendarDays size={19}/>Preorder up to 90 days ahead</span><span><ShoppingBag size={19}/>Choose your delivery date & time</span></div>
 <Reveal className="business-section occasion-section"><div><span className="dk-eyebrow">WHAT’S THE OCCASION?</span><h2>There’s always a reason<br/>to plan something good.</h2></div><div><div className="occasion-tabs" role="tablist" aria-label="Your occasion">{Object.keys(occasions).map(key=><button role="tab" aria-selected={occasion===key} key={key} onClick={()=>setOccasion(key)}>{key}</button>)}</div><p role="tabpanel" aria-live="polite">{occasions[occasion]}</p><Link className="text-link" to="/menu">Find something for your table <ArrowUpRight size={16}/></Link></div></Reveal>
 <Reveal className="business-section"><div className="section-heading"><div><span className="dk-eyebrow">FROM THE CURRENT MENU</span><h2>Your next “that looks good”.</h2></div><Link className="text-link" to="/menu">See the full menu <ArrowUpRight size={16}/></Link></div><div className="featured-foods">{featured.map(p=><Link key={p.id} to={`/products/${p.id}`} className="featured-food">{p.image_url?<img src={p.image_url} alt={p.name} loading="lazy"/>:<div className="food-image-empty"><ChefHat size={42}/></div>}<div><span>{p.category_name}</span><h3>{p.name}</h3><p>RM {Number(p.price).toFixed(2)} <ArrowUpRight size={19}/></p></div></Link>)}</div>{featured.length===0 && <p>The kitchen’s menu is being prepared. Check back soon or contact the owner.</p>}</Reveal>
 <Reveal className="business-story-teaser"><div><span className="dk-eyebrow">BEHIND EVERY MENU, A PERSON</span><h2>{store.founder_name?`Meet ${store.founder_name}.`:'More than a menu. A kitchen to get to know.'}</h2><p>{store.founder_intro || 'Food is personal. So should be the way you order it. Get to know the owner, the food they love making, and the story behind this kitchen.'}</p><Link className="text-link" to="/story">Read our story <ArrowUpRight size={16}/></Link></div><div className="story-type-card"><span>From</span><strong>{store.name}</strong><span>to your table.</span></div></Reveal>
 <Reveal className="business-section"><div className="section-heading"><div><span className="dk-eyebrow">A SIMPLE WAY TO PREORDER</span><h2>From “what shall we eat?”<br/>to a plan you can see.</h2></div><Link to="/how-it-works" className="text-link">See how it works <ArrowUpRight size={16}/></Link></div><Steps/></Reveal>
 {store.bulk_discount_percent>0 && <Reveal className="business-offer"><span className="dk-eyebrow">BETTER TOGETHER</span><h2>{store.bulk_discount_percent}% off when you order {store.bulk_minimum}+ portions.</h2><p>Your qualifying food discount is applied automatically at checkout.</p><PrimaryLink>Plan a group order</PrimaryLink></Reveal>}
 <Reveal className="business-section"><span className="dk-eyebrow">BEFORE YOU ORDER</span><h2>A few things you might wonder.</h2><FAQ limit={3}/><Link className="text-link" to="/how-it-works">All questions & answers <ArrowUpRight size={16}/></Link></Reveal>
 </main>;
}
function Steps(){return <div className="business-steps">{[[ShoppingBag,'01','Find your favourite','Explore the current menu and add food to your basket.'],[CalendarDays,'02','Make a date','Choose delivery date and time. We check notice and daily capacity.'],[ChefHat,'03','Follow your order','The owner manages preparation. Follow progress in My Orders.']].map(([Icon,n,title,body])=><article key={n}><span className="step-number">{n}</span><Icon size={27}/><h3>{title}</h3><p>{body}</p></article>)}</div>}
export function StoryPage(){
 const {store}=useStorefront();
 return <main className="business-page"><PageMeta title="Our story" description="Meet the person behind the kitchen and discover their food, inspiration and approach to cooking."/><Reveal className="business-page-heading"><span className="dk-eyebrow">OUR STORY</span><h1>A person.<br/>A kitchen.<br/><em>A reason to cook.</em></h1><p className="business-lead">{store.founder_intro || 'Get to know the people and purpose behind your food.'}</p></Reveal><Reveal className="founder-section"><div className="founder-portrait">{store.founder_image_url?<img src={store.founder_image_url} alt={store.founder_name?`${store.founder_name}, kitchen owner`:'The kitchen owner'}/>:<div className="portrait-placeholder"><ChefHat size={60}/><span>THE PERSON BEHIND<br/>{store.name}</span><p>Owner portrait to be added</p></div>}</div><div><span className="dk-eyebrow">MEET THE OWNER</span><h2>{store.founder_name || 'The face behind the food'}</h2><div className="story-prose">{store.founding_story ? store.founding_story.split('\n').filter(Boolean).map((p,i)=><p key={i}>{p}</p>):<p>The owner’s personal story has not been added yet. Their inspiration, beginnings and favourite moments belong here—in their own words.</p>}</div><Link className="text-link" to="/contact">Say hello to the kitchen <ArrowUpRight size={16}/></Link></div></Reveal><Reveal className="business-section story-details"><article><Heart size={25}/><span className="dk-eyebrow">WHY WE MAKE IT</span><h2>Food with a point of view.</h2><p>{store.food_philosophy || 'The owner will share their approach to cooking here. Ask the kitchen about ingredients or special requests before ordering.'}</p></article><article><ChefHat size={25}/><span className="dk-eyebrow">WHAT WE LOVE MAKING</span><h2>{store.signature_food || 'Discover the current menu.'}</h2><p>{store.signature_food?'Start with the kitchen’s signature food, then explore the rest of the menu.':'Browse available food and learn about each item directly from its menu description.'}</p><PrimaryLink/></article></Reveal></main>;
}
export function HowItWorksPage(){return <main className="business-page"><PageMeta title="How preordering works" description="Learn how to choose food, schedule delivery, track your order and ask the kitchen about special requests."/><Reveal className="business-page-heading"><span className="dk-eyebrow">FROM OUR KITCHEN TO YOUR PLANS</span><h1>A little planning.<br/><em>A simpler order.</em></h1><p className="business-lead">Choose the food first. Give it a date. Follow the preparation.</p></Reveal><Steps/><Reveal className="business-section timing-explainer"><Clock size={38}/><div><h2>Good timing starts before the order.</h2><p>Each menu has advance notice and cooking time. Checkout adds the owner’s travel and contingency buffer and checks daily portions before accepting your requested date.</p><p>Express is a request, not an automatic courier booking. For a strict event deadline, ask the owner to confirm arrangements first.</p></div><PrimaryLink>Start your order</PrimaryLink></Reveal><Reveal className="business-section"><span className="dk-eyebrow">LET’S CLEAR THAT UP</span><h2>Your questions, answered.</h2><FAQ/></Reveal></main>}
export function ContactPage(){
 const {store,error}=useStorefront();const [topic,setTopic]=useState('General enquiry'),[message,setMessage]=useState('');
 const text=`Hello ${store.name}, ${topic.toLowerCase()}: ${message}`;
 const whatsapp=store.whatsapp_number?`https://wa.me/${store.whatsapp_number}?text=${encodeURIComponent(text)}`:null;
 const email=store.contact_email?`mailto:${store.contact_email}?subject=${encodeURIComponent(topic)}&body=${encodeURIComponent(text)}`:null;
 return <main className="business-page"><PageMeta title="Contact the kitchen" description="Ask the owner about group orders, ingredients or your next occasion before preordering."/><Reveal className="business-page-heading"><span className="dk-eyebrow">LET’S TALK FOOD</span><h1>Something on<br/><em>your mind?</em></h1><p className="business-lead">A family gathering, a food question, or a date you’re planning around. Start a conversation with the kitchen.</p></Reveal><div className="contact-layout"><Reveal><h2>A direct line to the owner.</h2><div className="contact-detail"><MapPin/><div><h3>Service area</h3><p>{store.service_area || 'Ask the owner to confirm delivery availability for your address.'}</p></div></div>{store.contact_email && <div className="contact-detail"><Mail/><a href={`mailto:${store.contact_email}`}>{store.contact_email}</a></div>}{store.whatsapp_number && <div className="contact-detail"><MessageCircle/><a href={`https://wa.me/${store.whatsapp_number}`} target="_blank" rel="noreferrer">Chat with the kitchen on WhatsApp ↗</a></div>}{store.social_url && <a className="text-link" href={store.social_url} target="_blank" rel="noreferrer">See what’s happening in the kitchen <ArrowUpRight size={16}/></a>}<p className="dk-note">Need an answer about allergies? Check with the owner before placing an order.</p></Reveal><Reveal className="enquiry-card"><h2>What would you like to ask?</h2><label>Topic<select value={topic} onChange={e=>setTopic(e.target.value)}>{['General enquiry','Group order','Delivery date','Ingredients or allergies'].map(t=><option key={t}>{t}</option>)}</select></label><label>Your message<textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Tell us what you have in mind…" maxLength={2000}/></label>{whatsapp?<a className="dk-primary" target="_blank" rel="noreferrer" href={whatsapp}>Continue in WhatsApp <ArrowUpRight size={17}/></a>:email?<a className="dk-primary" href={email}>Open email enquiry <ArrowUpRight size={17}/></a>:<p role="status">{error || 'The owner has not added a contact channel yet. Contact details are being confirmed.'}</p>}<p className="dk-note">This opens your messaging app with a draft. Nothing is sent until you send it there.</p></Reveal></div><Reveal className="business-section contact-menu-cta"><h2>Already know what you fancy?</h2><p>The full menu and preorder checkout are ready when you are.</p><PrimaryLink/></Reveal></main>;
}
