import {apiError} from '../../utils/apiError';
import {useEffect,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {MapPin,CalendarDays,CreditCard,Check,ChevronLeft} from 'lucide-react';
import axios from 'axios';
import {useUI} from '../../contexts/UIProvider';
import {useCart} from '../../contexts/CartProvider';
import {useOrder} from '../../contexts/OrderProvider';
import {getCookie} from '../../utils/cookieUtils';
import './CheckoutPage.css';
const emptyAddress={recipient_name:'',line1:'',line2:'',city:'',state:'',postal_code:'',country:'Malaysia',phone:''};
const states=['Johor','Kedah','Kelantan','Melaka','Negeri Sembilan','Pahang','Penang','Perak','Perlis','Sabah','Sarawak','Selangor','Terengganu','Kuala Lumpur','Labuan','Putrajaya'];
const errorText=apiError;
export default function CheckoutPage(){
 const [quote,setQuote]=useState(null),[checking,setChecking]=useState(false);
 const [openedAt]=useState(()=>Date.now());
 const [address,setAddress]=useState(null),[draft,setDraft]=useState(emptyAddress),[editing,setEditing]=useState(false),[addressLoading,setAddressLoading]=useState(true),[saving,setSaving]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState({delivery_at:'',delivery_method:'standard',payment:'cod'});
 const {formatPrice}=useUI();const {cart,total,SHIPPING_FEE,finalTotal,discount,promotion}=useCart();const {placeOrder}=useOrder();const navigate=useNavigate();
 useEffect(()=>{let active=true;axios.get('/api/address/').then(r=>{if(active){setAddress(r.data);setDraft(r.data || emptyAddress);setEditing(!r.data);}}).catch(e=>{if(active)setError(errorText(e));}).finally(()=>{if(active)setAddressLoading(false);});return()=>{active=false};},[]);
 const notice=Math.max(0,...cart.map(i=>i.product.lead_hours ?? 24));const cooking=cart.reduce((n,i)=>{const p=i.product,batches=Math.ceil(i.quantity/(p.batch_size || 1));return n+(p.preparation_tasks?.length ? p.preparation_tasks.reduce((t,s)=>t+s.minutes+(batches-1)*s.additional_batch_minutes,0) : (p.preparation_minutes ?? 60)+(batches-1)*(p.additional_batch_minutes ?? 60)+i.quantity*(p.packing_minutes_per_portion ?? 1));},0);const buffer=promotion?.delivery_buffer_minutes ?? 90;
 const localInput=d=>new Date(d.getTime()+8*3600000).toISOString().slice(0,16);
 const earliest=localInput(new Date(openedAt+(notice*60+buffer)*60000));const latest=localInput(new Date(openedAt+90*86400000));
 const quoteKey=JSON.stringify([form.delivery_at,cart.map(i=>[i.id,i.quantity])]);
 const checkPlan=async()=>{if(!form.delivery_at || checking)return;setChecking(true);setError('');setQuote(null);try{const r=await axios.post('/api/orders/quote/',{delivery_at:form.delivery_at+':00+08:00'},{headers:{'X-CSRFToken':getCookie('csrftoken')}});setQuote({key:quoteKey,...r.data});}catch(e){setError(errorText(e))}finally{setChecking(false)}};
 const saveAddress=async e=>{e.preventDefault();setSaving(true);setError('');try{const r=await axios.put('/api/address/',draft,{headers:{'X-CSRFToken':getCookie('csrftoken')}});setAddress(r.data);setDraft(r.data);setEditing(false);}catch(e){setError(errorText(e));}finally{setSaving(false);}};
 const submit=async e=>{
  e.preventDefault();if(!address || editing || loading)return;
  setLoading(true);setError('');
  try {
   sessionStorage.setItem('deliveryPlan',JSON.stringify({delivery_at:form.delivery_at+':00+08:00',delivery_method:form.delivery_method}));
   if(form.payment!=='wallet'){
    await placeOrder(address.id,form.payment,{throwOnError:true});
    navigate('/orders',{state:{formPayment:true}});
   }else{
    localStorage.setItem('addressId',address.id);
    navigate('/payment/wallet',{state:{addressId:address.id}});
   }
  }catch(e){setError(errorText(e));}finally{setLoading(false);}
 };

 if(!cart.length)return <main className="checkout-container"><h1>Your basket is empty</h1><p>Add something from the menu before checking out.</p><Link className="dk-primary" to="/menu">Explore the menu</Link></main>;
 return <main className="checkout-container"><Link to="/cart" className="checkout-back"><ChevronLeft size={16}/>Back to basket</Link><h1 className="checkout-title">Almost at your table.</h1><p className="checkout-intro">Confirm your address, choose a delivery time, and place your preorder.</p>{error && <div role="alert" className="checkout-error">{error}</div>}<div className="checkout-grid"><div className="checkout-main">
 <section className="checkout-section"><div className="checkout-section-heading"><MapPin size={21}/><h2>Delivery address</h2>{address && !editing && <button type="button" onClick={()=>setEditing(true)}>Change</button>}</div>
 {addressLoading?<p role="status">Loading your saved address…</p>:editing?<form className="address-form" onSubmit={saveAddress}><p className="checkout-hint">Save once. We’ll use this address for your next orders too.</p><div className="address-fields">{[['recipient_name','Recipient name','name'],['phone','Phone number','tel'],['line1','Street address','address-line1'],['line2','Apartment, floor or unit (optional)','address-line2'],['city','City','address-level2'],['postal_code','Postcode','postal-code']].map(([key,label,auto])=><label key={key} className={['line1','line2'].includes(key)?'field-wide':''}>{label}<input type={key==='phone'?'tel':'text'} autoComplete={auto} required={key!=='line2'} pattern={key==='postal_code'?'[0-9]{5}':undefined} maxLength={key==='postal_code'?5:key==='phone'?20:150} value={draft[key] || ''} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<label>State / territory<select required autoComplete="address-level1" value={draft.state} onChange={e=>setDraft({...draft,state:e.target.value})}><option value="">Select a state</option>{states.map(s=><option key={s}>{s}</option>)}</select></label><label>Country<input value="Malaysia" readOnly autoComplete="country-name"/></label></div><div className="checkout-actions"><button className="checkout-submit" disabled={saving}>{saving?'Saving…':'Save delivery address'}</button>{address && <button type="button" onClick={()=>{setDraft(address);setEditing(false)}}>Cancel</button>}</div></form>:address?<div className="saved-address"><span className="address-default"><Check size={14}/>Saved address</span><strong>{address.recipient_name || 'Delivery recipient'}</strong><p>{address.phone}</p><p>{address.line1}{address.line2 && <><br/>{address.line2}</>}<br/>{address.postal_code} {address.city}, {address.state}<br/>{address.country}</p><p className="checkout-hint">Changing your saved address won’t alter orders already placed.</p></div>:<button onClick={()=>setEditing(true)}>Add delivery address</button>}</section>
 <form onSubmit={submit} className="checkout-form"><section className="checkout-section"><div className="checkout-section-heading"><CalendarDays size={21}/><h2>Delivery plan</h2></div><div className="checkout-timing"><span>{notice}h advance notice</span><span>{cooking} min total recipe steps</span><span>{buffer} min delivery buffer</span></div><label>Requested date and time<input type="datetime-local" required min={earliest} max={latest} value={form.delivery_at} onChange={e=>setForm({...form,delivery_at:e.target.value})}/><span className="checkout-hint">Malaysia time · 9am–9pm · up to 90 days ahead</span></label><button type="button" disabled={!form.delivery_at || checking} onClick={checkPlan}>{checking?'Checking kitchen availability...':'Check availability'}</button>{quote?.key===quoteKey && <p className="checkout-hint" role="status">Kitchen time available. Preparation starts {new Date(quote.preparation_at).toLocaleString('en-MY',{timeZone:'Asia/Kuala_Lumpur'})}. {quote.hands_on_minutes} minutes of hands-on work. Availability is checked again when you place your order.</p>}<label>Delivery service<select value={form.delivery_method} onChange={e=>setForm({...form,delivery_method:e.target.value})}><option value="standard">Owner delivery</option><option value="express">Request express delivery</option></select><span className="checkout-hint">{form.delivery_method==='express'?'The owner must confirm courier availability and any extra charge. Menu lead times still apply.':'The owner confirms your requested delivery arrangements.'}</span></label></section>
 <section className="checkout-section"><div className="checkout-section-heading"><CreditCard size={21}/><h2>Payment</h2></div><div className="payment-options">{[['cod','Cash on delivery','Pay when your order arrives.'],...(promotion?.manual_payment_enabled?[['manual','DuitNow QR / bank transfer','Transfer after placing the order. The owner verifies receipt before marking it paid.']]:[]),['wallet','Demo credit wallet','For project demonstrations. No real money or blockchain transfer.']].map(([value,title,subtitle])=><label key={value} className={form.payment===value?'selected':''}><input type="radio" name="payment" value={value} checked={form.payment===value} onChange={()=>setForm({...form,payment:value})}/><span><strong>{title}</strong><small>{subtitle}</small></span></label>)}</div><p className="checkout-hint">Smart-contract escrow is not enabled for live payments. <Link to="/escrow-demo">Explore the testnet demo</Link></p></section>
 <button className="checkout-submit" disabled={loading || addressLoading || !address || editing}>{loading?'Placing order…':form.payment!=='wallet'?`Place preorder · ${formatPrice(finalTotal)}`:'Continue to demo wallet'}</button>{(!address || editing) && <p className="checkout-hint">Save your delivery address to continue.</p>}</form></div>
 <aside className="checkout-summary"><h2>Your preorder</h2>{cart.map(item=><div className="checkout-summary-item" key={item.id}><div><strong>{item.product.name}</strong><span>Quantity: {item.quantity}</span></div><strong>{formatPrice(item.product.price*item.quantity)}</strong></div>)}<dl><div><dt>Food subtotal</dt><dd>{formatPrice(total)}</dd></div>{discount>0 && <div><dt>Bulk discount</dt><dd>−{formatPrice(discount)}</dd></div>}<div><dt>Delivery</dt><dd>{SHIPPING_FEE?formatPrice(SHIPPING_FEE):'Free'}</dd></div><div className="checkout-total"><dt>Total</dt><dd>{formatPrice(finalTotal)}</dd></div></dl>{total<50 && <p className="checkout-hint">Add {formatPrice(50-total)} in food for free delivery.</p>}<p className="checkout-hint">Your order status will appear in My Orders after checkout.</p></aside></div></main>;
}
