import {useEffect,useMemo,useState} from 'react';
import axios from 'axios';
import {Link} from 'react-router-dom';
import KitchenAvailability from '../../components/KitchenAvailability';
import {apiError} from '../../utils/apiError';
const dateKey=d=>new Date(d).toLocaleDateString('en-CA',{timeZone:'Asia/Kuala_Lumpur'});
const display=d=>d?new Date(d).toLocaleString('en-MY',{timeZone:'Asia/Kuala_Lumpur'}):'Not scheduled';
const stamp=d=>new Date(d).toISOString().replace(/[-:]/g,'').split('.')[0]+'Z';
export default function PlannerPage(){
 const [month,setMonth]=useState(new Date().toISOString().slice(0,7));
 const [plan,setPlan]=useState(null),[error,setError]=useState(''),[date,setDate]=useState(''),[mode,setMode]=useState('delivery_at'),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');axios.get('/api/admin/planning/',{signal:c.signal}).then(r=>setPlan(r.data)).catch(e=>{if(!axios.isCancel(e))setError(apiError(e))}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort();},[retry]);
 const orders=plan?.orders || [];
 const upcoming=orders.filter(o=>!date || (o[mode] && dateKey(o[mode])===date)).sort((a,b)=>new Date(a[mode] || 0)-new Date(b[mode] || 0));
 const counts=useMemo(()=>{const result={};for(const o of plan?.orders || [])if(o[mode]){const key=dateKey(o[mode]);result[key]=(result[key] || 0)+1}return result},[plan,mode]);
 const offset=(new Date(month+'-01T12:00:00+08:00').getUTCDay()+6)%7;
 const monthDays=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate();
 const exportCalendar=()=>{
  const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Dapur Kita//Planner//EN'];
  for(const o of orders)for(const [key,label] of [['preparation_at','Prepare'],['delivery_at','Deliver']])if(o[key])lines.push('BEGIN:VEVENT',`UID:${o.id}-${key}@dapur-kita`,`DTSTAMP:${stamp(new Date())}`,`DTSTART:${stamp(o[key])}`,`DTEND:${stamp(key==='preparation_at' && o.preparation_end_at ? o.preparation_end_at : new Date(new Date(o[key]).getTime()+30*60000))}`,`SUMMARY:${label} order ${o.id}`,'BEGIN:VALARM','TRIGGER:-PT30M','ACTION:DISPLAY',`DESCRIPTION:${label} order ${o.id}`,'END:VALARM','END:VEVENT');
  lines.push('END:VCALENDAR');const url=URL.createObjectURL(new Blob([lines.join('\r\n')],{type:'text/calendar'}));const a=document.createElement('a');a.href=url;a.download='kitchen-orders.ics';a.click();URL.revokeObjectURL(url);
 };
 return <main className="dk-workspace"><h1>Preparation planner</h1><p>Plan ingredients, kitchen work and delivery. All times are Malaysia time.</p>
 <div className="dk-actions"><button disabled={loading} onClick={()=>setRetry(n=>n+1)}>{loading?'Loading...':'Refresh plan'}</button><button disabled={!plan || loading} onClick={exportCalendar}>Export calendar</button></div>
 {error && <p role="alert">{error} Use Refresh plan to retry.</p>}{loading && <p role="status">Loading kitchen plan...</p>}
 <div className="dk-actions"><label>View by<select value={mode} onChange={e=>setMode(e.target.value)}><option value="delivery_at">Delivery date</option><option value="preparation_at">Preparation starts</option><option value="created_at">Order date</option></select></label><label>Filter date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button onClick={()=>setDate('')}>All dates</button></div>
 <section className="dk-calendar"><div className="dk-actions"><h2>Kitchen calendar</h2><label>Month<input type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value)}}/></label></div><div className="dk-calendar-grid">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=><strong key={d}>{d}</strong>)}{Array.from({length:offset},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:monthDays},(_,i)=>{const key=month+'-'+String(i+1).padStart(2,'0');const count=counts[key] || 0;return <button className={date===key?'selected':''} key={key} onClick={()=>setDate(key)} aria-label={`${key}, ${count} orders`}><span>{i+1}</span>{count>0 && <small>{count} orders</small>}</button>})}</div></section>
 <p className="dk-note">Calendar counts show the selected date type, not every occupied day. Expand preparation steps for work spanning multiple days. Calendar exports are snapshots with 30-minute reminders; re-export after changes.</p>
 <div className="dk-planner-grid"><section><h2>Upcoming work</h2><p>One worker and one of each equipment type. Unattended work can overlap when equipment differs. Existing bookings keep their accepted schedule.</p>{!loading && !error && upcoming.length===0 && <p>No orders for this view.</p>}
 {upcoming.map(o=><article className="dk-panel" key={o.id}><div className="dk-eyebrow">ORDER #{o.id} / {o.status} / {o.delivery_method}</div><h3>{o.items.map(i=>`${i.quantity} x ${i.product_name}`).join(', ')}</h3><p>Prepare: {display(o.preparation_at)}</p><p>Ready: {display(o.preparation_end_at)}</p><p>Deliver: {display(o.delivery_at)}</p>{o.preparation_at && new Date(o.preparation_at)<new Date() && ['pending','processing'].includes(o.status) && <strong className="dk-warning">Preparation due - check this order</strong>}
 {o.preparation_plan?.tasks?.length>0?<details className="scheduled-tasks"><summary>Preparation steps / {o.preparation_plan.hands_on_minutes} min hands-on</summary><ol>{o.preparation_plan.tasks.map((t,i)=><li key={i}><strong>{t.menu}: {t.name}</strong><span>{display(t.start)} to {display(t.end)}</span><span>{t.minutes} min / {t.resource.replaceAll('_',' ')} / {t.worker?'Worker needed':'Unattended'}</span></li>)}</ol></details>:<p className="dk-note">Earlier booking: no task breakdown recorded. Its preparation window reserves the whole kitchen.</p>}
 <div className="dk-actions"><Link to="/admin/orders">Manage order</Link>{o.delivery_method==='express' && <a href="https://www.grab.com/my/express/" target="_blank" rel="noreferrer">Arrange GrabExpress externally</a>}{o.address && <a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent([o.address.line1,o.address.city,o.address.postal_code,'Malaysia'].join(', '))}`}>Delivery directions</a>}</div></article>)}</section>
 <aside><KitchenAvailability/><h2>Shopping shortfalls</h2><p>Allocates current stock once, earliest expiry first. Batches must remain within their recorded expiry through planned preparation.</p>{plan?.shopping.length===0 && <p>No shortfalls for recorded recipes.</p>}{plan?.shopping.map((s,i)=><article className="dk-panel" key={i}><strong>{s.material}: {s.quantity} {s.unit}</strong><p>Needed by {s.needed_by} / order #{s.order}</p></article>)}<p>Menus without recipes need a recipe before shopping needs can be calculated.</p><h2>Demand estimate</h2><article className="dk-panel"><strong>{plan?.forecast.next_7_days_portions ?? 'Not enough history'} {plan?.forecast.next_7_days_portions!=null && 'portions / next 7 days'}</strong><p>{plan?.forecast.method}</p>{plan?.forecast.validation_mae!=null && <p>Holdout average error: {plan.forecast.validation_mae} portions per day. Future error may differ.</p>}<p>Use confirmed orders first. This estimate is not a purchasing commitment.</p></article></aside></div></main>;
}
