import {useEffect, useState} from 'react';
import axios from 'axios';
import {Link} from 'react-router-dom';
const dateKey=d=>new Date(d).toLocaleDateString('en-CA',{timeZone:'Asia/Kuala_Lumpur'});
const stamp=d=>new Date(d).toISOString().replace(/[-:]/g,'').split('.')[0]+'Z';
export default function PlannerPage(){
 const [month,setMonth]=useState(new Date().toISOString().slice(0,7));
 const [orders,setOrders]=useState([]),[plan,setPlan]=useState(null),[error,setError]=useState(''),[date,setDate]=useState(''),[mode,setMode]=useState('delivery_at');
 useEffect(()=>{Promise.all([axios.get('/api/admin/orders/'),axios.get('/api/admin/planning/')]).then(([a,b])=>{setOrders(a.data);setPlan(b.data)}).catch(()=>setError('Could not load planning data. Please refresh.'));},[]);
 const active=orders.filter(o=>!['cancelled','delivered'].includes(o.status));
 const upcoming=active.filter(o=>!date || (o[mode] && dateKey(o[mode])===date)).sort((a,b)=>new Date(a[mode] || 0)-new Date(b[mode] || 0));
 const monthStart=new Date(month+'-01T12:00:00+08:00');
 const offset=(monthStart.getUTCDay()+6)%7;
 const monthDays=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate();
 const exportCalendar=()=>{
  const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Dapur Kita//Planner//EN'];
  for(const o of active) for(const [key,label] of [['preparation_at','Prepare'],['delivery_at','Deliver']]) if(o[key]) lines.push('BEGIN:VEVENT',`UID:${o.id}-${key}@dapur-kita`,`DTSTAMP:${stamp(new Date())}`,`DTSTART:${stamp(o[key])}`,`DTEND:${stamp(new Date(new Date(o[key]).getTime()+30*60000))}`,`SUMMARY:${label} order ${o.id}`,'BEGIN:VALARM','TRIGGER:-PT30M','ACTION:DISPLAY',`DESCRIPTION:${label} order ${o.id}`,'END:VALARM','END:VEVENT');
  lines.push('END:VCALENDAR');const url=URL.createObjectURL(new Blob([lines.join('\r\n')],{type:'text/calendar'}));const a=document.createElement('a');a.href=url;a.download='dapur-kita-orders.ics';a.click();URL.revokeObjectURL(url);
 };
 return <main className="dk-workspace"><span className="dk-eyebrow">YOUR KITCHEN, ONE PLAN</span><h1>Preparation planner</h1><p>Plan ingredients, cooking and deliveries. All times are Malaysia time.</p>
 {error && <p role="alert">{error}</p>}
 <div className="dk-actions"><label>View by<select value={mode} onChange={e=>setMode(e.target.value)}><option value="delivery_at">Delivery date</option><option value="preparation_at">Preparation date</option><option value="created_at">Order date</option></select></label><label>Filter date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button onClick={()=>setDate('')}>All dates</button><button onClick={exportCalendar}>Export calendar & reminders</button></div>
 <p className="dk-note">Import the calendar into your calendar app for 30-minute reminders. Re-export after schedule changes. This is a snapshot, not a live subscription.</p>
 <section className="dk-calendar"><div className="dk-actions"><h2>Kitchen calendar</h2><label>Month<input type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value)}}/></label></div><div className="dk-calendar-grid">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=><strong key={d}>{d}</strong>)}{Array.from({length:offset},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:monthDays},(_,i)=>{const key=month+'-'+String(i+1).padStart(2,'0');const count=active.filter(o=>o[mode] && dateKey(o[mode])===key).length;return <button className={date===key?'selected':''} key={key} onClick={()=>setDate(key)} aria-label={`${key}, ${count} orders`}><span>{i+1}</span>{count>0 && <small>{count} orders</small>}</button>})}</div></section>
 <div className="dk-planner-grid"><section><h2>Upcoming work</h2>{upcoming.length===0 && <p>No orders for this view.</p>}{upcoming.map(o=><article className="dk-panel" key={o.id}><div className="dk-eyebrow">ORDER #{o.id} · {o.status} · {o.delivery_method}</div><h3>{o.items.map(i=>`${i.quantity} × ${i.product_name}`).join(', ')}</h3><p>Prepare: {o.preparation_at ? new Date(o.preparation_at).toLocaleString('en-MY',{timeZone:'Asia/Kuala_Lumpur'}):'Not scheduled'}</p><p>Deliver: {o.delivery_at ? new Date(o.delivery_at).toLocaleString('en-MY',{timeZone:'Asia/Kuala_Lumpur'}):'Not scheduled'}</p>{o.preparation_at && new Date(o.preparation_at)<new Date() && ['pending','processing'].includes(o.status) && <strong className="dk-warning">Preparation due — check this order</strong>}<div className="dk-actions"><Link to="/admin/orders">Manage order</Link>{o.address && <a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent([o.address.line1,o.address.city,o.address.postal_code,'Malaysia'].join(', '))}`}>Open delivery directions ↗</a>}</div></article>)}</section>
 <aside><h2>Shopping shortfalls</h2><p>Allocates current stock once, in preparation order, excluding batches that expire before cooking.</p>{plan?.shopping.length===0 && <p>No ingredient shortfalls for recorded recipes.</p>}{plan?.shopping.map((s,i)=><article className="dk-panel" key={i}><strong>{s.material} · {s.quantity} {s.unit}</strong><p>Needed by {s.needed_by} · order #{s.order}</p></article>)}<p>Menus without recipes need a recipe before their shopping needs can be calculated.</p><h2>Demand estimate</h2><article className="dk-panel"><strong>{plan?.forecast.next_7_days_portions ?? '—'} portions / next 7 days</strong><p>{plan?.forecast.method}</p><p>Based on {plan?.forecast.observed_portions_28_days ?? 0} paid portions in the last 28 days. Little history means a weak estimate.</p></article></aside></div></main>;
}
