import {useEffect,useState} from 'react';
import axios from 'axios';
import {getCookie} from '../../utils/cookieUtils';
export default function StoreSettingsPage(){
 const [store,setStore]=useState(null),[message,setMessage]=useState('');
 useEffect(()=>{axios.get('/api/storefront/').then(r=>setStore(r.data)).catch(()=>setMessage('Could not load settings.'));},[]);
 const save=async e=>{e.preventDefault();try{await axios.patch('/api/storefront/',store,{headers:{'X-CSRFToken':getCookie('csrftoken')}});window.dispatchEvent(new Event('storefront-updated'));setMessage('Saved. Your storefront and checkout now use these settings.');}catch(e){setMessage(JSON.stringify(e.response?.data || 'Save failed.'));}};
 return <main className="dk-workspace"><span className="dk-eyebrow">MAKE IT YOUR OWN</span><h1>Your kitchen settings</h1><p>Tell your actual story in your own words. Add only confirmed facts and real business images. Leave unconfirmed fields empty; do not invent awards, reviews or guarantees.</p>{store && <form className="dk-settings" onSubmit={save}>{[['name','Kitchen name'],['tagline','Tagline'],['story','Kitchen introduction'],['founder_name','Owner name'],['founder_intro','Owner introduction (one sentence)'],['founding_story','Your real business story: why you started, the first steps, what matters now'],['food_philosophy','Your approach to food'],['signature_food','Signature food'],['service_area','Confirmed service / delivery area'],['whatsapp_number','WhatsApp number (country code and digits only)'],['founder_image_url','Real owner portrait URL'],['social_url','Social media URL'],['contact_email','Contact email'],['delivery_buffer_minutes','Travel + contingency buffer (minutes)'],['bulk_minimum','Bulk promotion minimum portions'],['bulk_discount_percent','Bulk discount percent (0 disables, maximum 50)']].map(([key,label])=><label key={key}>{label}{['story','founding_story','food_philosophy'].includes(key)?<textarea value={store[key]} onChange={e=>setStore({...store,[key]:e.target.value})}/>:<input type={['delivery_buffer_minutes','bulk_minimum','bulk_discount_percent'].includes(key)?'number':['social_url','founder_image_url'].includes(key)?'url':key==='contact_email'?'email':'text'} min={key==='bulk_discount_percent'?0:1} max={key==='bulk_discount_percent'?50:undefined} value={store[key]} onChange={e=>setStore({...store,[key]:e.target.value})}/>}</label>)}<button>Save settings</button></form>}<section className="dk-panel"><h2>Owner reminders</h2><p>Use Planner → Export calendar for calendar notifications. Optional email reminders require SMTP configuration and a scheduled reminder worker; they are not enabled automatically.</p></section><p role="status">{message}</p></main>;
}
