import ReminderStatus from '../../components/ReminderStatus';
import {useEffect,useState} from 'react';
import axios from 'axios';
import {apiError} from '../../utils/apiError';
import {getCookie} from '../../utils/cookieUtils';
const groups=[
 {title:'Kitchen hours & delivery',help:'Hands-on work fits within these hours. Block closures and breaks in Planner.',fields:[['kitchen_open_hour','Opens at (hour, 0-22)','number',0,22],['kitchen_close_hour','Closes at (hour, 1-23)','number',1,23],['delivery_buffer_minutes','Travel and contingency (minutes)','number',1,1440]]},
 {title:'Storefront identity',help:'The essentials customers see first.',fields:[['name','Kitchen name'],['tagline','Short introduction'],['service_area','Delivery area'],['contact_email','Contact email','email'],['whatsapp_number','WhatsApp number including country code'],['social_url','Social media link','url']]},
 {title:'Your business story',help:'Tell customers who cooks their food and why you started. Use your real story and photos.',collapse:true,fields:[['story','Kitchen introduction','textarea'],['founder_name','Owner name'],['founder_intro','Owner introduction'],['founding_story','How your business started','textarea'],['food_philosophy','Your approach to food','textarea'],['signature_food','Signature food'],['founder_image_url','Owner photo URL','url']]},
 {title:'Manual payments',help:'These details are public when customers view your store. Use a business account. Verify incoming transfers in your bank before marking orders paid.',fields:[['bank_transfer_instructions','Bank name, account holder and payment instructions','textarea'],['duitnow_qr_url','DuitNow QR image URL','url']]},
 {title:'Bulk promotion',help:'Set the discount to 0 to switch off the promotion.',collapse:true,fields:[['bulk_minimum','Minimum portions','number',1,10000],['bulk_discount_percent','Discount (%)','number',0,50]]}
];
export default function StoreSettingsPage(){
 const [store,setStore]=useState(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{const c=new AbortController();setError('');axios.get('/api/storefront/',{signal:c.signal}).then(r=>setStore(r.data)).catch(e=>{if(!axios.isCancel(e))setError(apiError(e))});return()=>c.abort()},[retry]);
 const save=async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');setMessage('');try{const r=await axios.patch('/api/storefront/',store,{headers:{'X-CSRFToken':getCookie('csrftoken')}});setStore(r.data);window.dispatchEvent(new Event('storefront-updated'));setMessage('Settings saved. Existing order schedules are unchanged.');}catch(e){setError(apiError(e))}finally{setBusy(false)}};
 const fields=g=><><p>{g.help}</p><div className="admin-fields">{g.fields.map(([key,label,type='text',min,max])=><label key={key} style={type==='textarea'?{gridColumn:'1 / -1'}:undefined}>{label}{type==='textarea'?<textarea value={store[key] || ''} onChange={e=>setStore({...store,[key]:e.target.value})}/>:<input type={type} min={min} max={max} value={store[key] ?? ''} onChange={e=>setStore({...store,[key]:e.target.value})}/>}</label>)}</div></>;
 return <main className="dk-workspace"><div className="admin-page-heading"><div><span className="admin-kicker">YOUR BUSINESS</span><h1>Settings</h1><p>Manage kitchen availability, storefront details and promotions.</p></div></div>{error && <div role="alert" className="admin-notice error">{error}<button onClick={()=>setRetry(n=>n+1)}>Reload settings</button></div>}{!store && !error && <p role="status">Loading settings...</p>}{store && <form onSubmit={save} className="dk-settings">{groups.map(g=>g.collapse?<details className="settings-group" key={g.title}><summary>{g.title}</summary>{fields(g)}</details>:<section className="settings-group" key={g.title}><h2>{g.title}</h2>{fields(g)}</section>)}<label><input type="checkbox" checked={!!store.manual_payment_enabled} onChange={e=>setStore({...store,manual_payment_enabled:e.target.checked})}/> Enable manual DuitNow / bank transfer at checkout</label><div className="admin-toolbar"><button className="admin-primary" disabled={busy}>{busy?'Saving...':'Save settings'}</button><span role="status">{message}</span></div></form>}<ReminderStatus/></main>;
}
